version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./datadir:/data/db
    environment:
      MONGO_INITDB_DATABASE: Flickbase
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 27017:27017
  my-flickbase:
    image: my-flickbase:latest
    ports:
      - 3000:80
  my-flickbase-backend:
    image: my-flickbase-backend:latest
    env_file:
      - .env
    # environment:
    #   MONGODB_URI: mongodb://mongodb:27017/Flickbase
    depends_on:
      - mongodb
    ports:
      - 3001:3001